const mutations = {
  IS_LOGED_IN: "IS_LOGED_IN",
  LOGING_LOADER: "LOGING_LOADER",
  IS_FIRST_LOGIN: "IS_FIRST_LOGIN",
  SHOW_NOTIFY: "SHOW_NOTIFY",
  USER: "USER",
  USER_CONTACTS: "USER_CONTACTS",
  CHATS_LIST: "CHATS_LIST",
  NEW_CHAT: "NEW_CHAT",

  SELECTED_CHAT_ID: "SELECTED_CHAT_ID",
  CURRENT_CHAT: "CURRENT_CHAT",
  CURRENT_CHAT_MSGS: "CURRENT_CHAT_MSGS",
  NEW_MSGS: "NEW_MSGS",
  USER_NEW_MSGS: "USER_NEW_MSGS",
  ADD_USER_NEW_MSGS: "ADD_USER_NEW_MSGS",
  CHAT_MEMBERS: "CHAT_MEMBERS",
};

export default mutations;
