const mutations = {
  IS_LOGED_IN: "IS_LOGED_IN",
  LOGING_LOADER: "LOGING_LOADER",
  IS_FIRST_LOGIN: "IS_FIRST_LOGIN",
  SHOW_NOTIFY: "SHOW_NOTIFY",
  USER: "USER",
  CHATS_LIST: "CHATS_LIST",
  SELECTED_CHAT_ID: "SELECTED_CHAT_ID",
  CURRENT_CHAT: "CURRENT_CHAT",
  CURRENT_CHAT_MSGS: "CURRENT_CHAT_MSGS",
  NEW_MSGS: "NEW_MSGS",
};

export default mutations;
